<?php

function sahirastha_get_insurance_services_data(): array
{
    $json = <<<'JSON'
[
  {
    "num": 1,
    "title": "Unclaimed Maturity & Survival Benefits",
    "sections": {
      "Hero Section": "Page headline: Recover Unclaimed Insurance Maturity and Survival Benefits\nSubheadline: If a policy matured, a money-back payout fell due, or an insurance amount should have reached you but did not, Sahirasta helps you understand the issue, organise the records, and move the matter toward release.\nSupport line: We assist policyholders, widows, legal heirs, families, senior citizens, and NRIs dealing with old LIC or private-insurer policies, missing paperwork, outdated bank details, or legacy record problems.\nPrimary CTA: Request a Case Review\nSecondary CTA: See Documents Usually Required",
      "What Is This Service?": "This service is for cases where an insurance amount became payable but never actually reached the right person. The policy may have matured long ago, a survival benefit may have fallen due under a money-back plan, or the insurer may have processed the amount but payment failed, remained unclaimed, or could not be completed because the records were outdated or incomplete.\nAn unpaid insurance amount is not always dramatic. Sometimes the issue is a missing discharge form, an old address, a bank account that no longer exists, or a policy that sat quietly in the background while the family assumed everything had already been handled. In other cases, the policyholder died, papers were scattered, and no one knows whether any maturity or survival amount was still pending.\nThis page is not about selling new insurance. It is about tracing, clarifying, and moving forward on amounts that should already have been paid under an existing policy.",
      "When Does This Issue Usually Arise?": "A policy matured years ago and the policyholder never received the maturity proceeds.\nA money-back or survival benefit was due but no credit ever appeared in the bank account.\nThe insurer sent a cheque that was never received, not encashed, or returned unpaid.\nThe policyholder changed address, bank account, contact number, or KYC details and the insurer could not complete payment.\nA family finds policy papers after a death and is unsure whether any maturity or survival amount is still pending.\nThe records are old enough that nobody is certain whether the amount was paid, reversed, kept in an unclaimed pool, or blocked by a mismatch.",
      "Who Typically Needs Help With This?": "Policyholders with old LIC or private-insurer policies that have matured or should have paid periodic benefits.\nSenior citizens who hold legacy policies with outdated servicing records.\nWidows, children, or other family members reviewing older insurance papers after a death.\nNRIs handling Indian insurance policies from abroad.\nFamilies that have partial information — a policy number, a bond, a receipt, or a premium trail — but no clear view of what is still payable.",
      "How Sahirasta Helps": "Sahirasta starts by separating three different possibilities that people often confuse: whether the policy genuinely reached a payout stage, whether the amount was already paid, and whether the real problem is not the benefit itself but a servicing or entitlement blockage.\nOnce that basic classification is clear, the practical work usually involves reviewing policy details, checking available records, identifying whether the issue is maturity, survival benefit, bank/KYC mismatch, nominee or legal-heir complication, or insurer-side record friction, and then preparing the right follow-up path.\nIn straightforward cases, the problem is often last-mile servicing: old bank details, missing discharge requirements, or broken communication. In more difficult cases, the issue becomes record reconstruction, entitlement proof, or confirmation of whether the amount is actually still outstanding.\nSahirasta helps clients organise the file, identify what is missing, understand what the insurer is likely to ask for, and move the case toward release with a more disciplined approach than ad hoc chasing.",
      "Documents Usually Required": "The exact document set depends on the policy, the insurer, and whether the policyholder is alive, deceased, or being represented by a family member. Commonly relevant documents include:\nPolicy bond, policy number, premium receipt, or any available insurer correspondence.\nIdentity and address proof of the policyholder or claimant.\nPAN, KYC, and bank proof, including cancelled cheque, where payout has to be re-routed.\nClaim or discharge forms if the insurer requires them for the type of payout involved.\nDeath certificate and proof of entitlement where the original policyholder is deceased.\nNominee records, legal-heir documents, succession papers, or relationship proof where the claim route is not straightforward.\nOverseas identity and address support where the claimant is an NRI.\nIt is better to begin with the papers available than to wait for a perfect file. Many cases become clearer only after the first round of review.",
      "Why These Cases Stay Unpaid or Get Stuck": "Older insurance payouts often remain unresolved for reasons that are more boring than people expect, but no less frustrating. The most common problems are outdated bank details, returned cheques, unsubmitted discharge requirements, old addresses, missing contact updates, or policyholder records that no longer match current identity documents.\nIn family cases, the difficulty grows when a policyholder has died and the family is not sure whether the issue is a maturity amount, a survival benefit, a death claim, or a record mismatch. The paperwork may not clearly state the current status, and the insurer may not act until the claimant route is clear.\nSome cases also stall because the policyholder or family assumes that the insurer will automatically push the money through. That is not always how it works. A payable amount may still sit unresolved if the insurer lacks updated bank details, completed servicing forms, or a clear claimant.",
      "Special Notes for Widows, Legal Heirs, and NRIs": "Many unresolved insurance matters surface only when a widow, son, daughter, or other family member begins sorting old documents after a death. The immediate question is often not legal theory but practical confusion: was this policy already paid, is something still due, and who is the right person to pursue it?\nNRIs often face an added layer of difficulty because the policy, branch, or claimant records are in India while the person handling the matter is abroad. That can mean more identity documentation, more coordination, and more dependence on well-organised paperwork, but it does not automatically make the case impossible.\nIn both family and NRI situations, incomplete papers do not automatically end the matter. They simply change the route. The real task is to work out whether the case is a payout trace, a servicing correction, an entitlement issue, or a combination of all three.",
      "Frequently Asked Questions": "How do I know whether a maturity or survival amount is still unpaid?\nThe starting point is to identify the policy status, due date, and whether any payment trail exists. Sometimes the amount is still unresolved; sometimes it was processed but never reached the right account; and sometimes the real problem is a records mismatch.\nWhat if I do not have the original policy bond?\nThe lack of the original bond does not automatically end the case. Other records such as policy numbers, receipts, insurer letters, or claimant identity documents may still help rebuild the file.\nCan family members pursue an unpaid maturity amount after the policyholder has died?\nYes, but the route may shift into nominee or legal-heir territory depending on the facts and the insurer’s requirements.\nCan NRIs pursue old Indian insurance payouts?\nYes. Additional documentation may be needed, but many cases can still be handled through a structured remote process.\nWhat if I am not even sure whether the amount is still outstanding?\nThat uncertainty is common. A realistic review often begins with exactly that question.",
      "Final Call to Action": "If an insurance policy matured, a survival benefit was due, or an amount seems to have disappeared into old records, waiting rarely improves the file. Addresses change, bank details go stale, branches move, and family knowledge fades.\nWhether you have a full set of papers or only partial information, Sahirasta can review the case and help you understand the next practical step.\nRequest a Case Review"
    },
    "slug": "insurance-unclaimed-maturity-survival-benefits"
  },
  {
    "num": 2,
    "title": "Death Claim Support",
    "sections": {
      "Hero Section": "Page headline: Get Support With Insurance Death Claims\nSubheadline: When a policyholder has died and the claim process feels unclear, delayed, or blocked, Sahirasta helps families, widows, legal heirs, and NRIs organise the case and move it forward with practical clarity.\nSupport line: We assist in understanding the likely route, identifying missing documents, and reducing the confusion that often follows a death-related insurance claim.\nPrimary CTA: Request a Case Review\nSecondary CTA: See Documents Usually Required",
      "What Is This Service?": "This service is for cases where an insurance amount may become payable after the death of the policyholder and the family needs help understanding how to proceed. In some cases the route is straightforward because the nominee details are clear and the insurer’s records are in order. In many others, the file is messier: there may be more than one possible claimant, outdated records, missing papers, uncertainty about policy status, or confusion about what the insurer is actually asking for.\nA death claim is not only a paperwork issue. Families are often dealing with grief, incomplete financial information, and pressure to make sense of old records quickly. Sahirasta’s role is to bring order to the situation, help identify the likely claim route, and support the family through the practical steps needed to move the matter forward.\nThis page is not about selling insurance or giving emotional slogans. It is about helping families handle a difficult claim situation with structure, seriousness, and realistic expectations.",
      "When Does This Issue Usually Arise?": "A spouse, parent, or other family member dies and the family discovers an insurance policy but does not know how to make the claim.\nThe nominee is recorded, but the paperwork is incomplete or the insurer asks for additional clarification.\nNo nominee was registered, the nominee has also died, or the family is unsure who is legally entitled to proceed.\nThe insurer raises questions about policy status, premium payment history, assignment, loan, or other record issues before processing the claim.\nThe claimant is abroad, the family is spread across locations, or the branch that issued the policy is different from where the family is now trying to follow up.",
      "Who Typically Needs Help With This?": "Widows, widowers, sons, daughters, and other close family members trying to process an insurance claim after a death.\nLegal heirs where the nominee route is unclear, disputed, outdated, or unavailable.\nFamilies handling older LIC or private-insurer policies with incomplete records.\nNRIs dealing with Indian insurance claims remotely after the death of a parent, spouse, or relative.\nClients who have partial documents but do not know whether the issue is a simple death claim, a nominee problem, a record mismatch, or a wider succession issue.",
      "How Sahirasta Helps": "Sahirasta begins by clarifying what kind of case this actually is. That matters because families often describe everything as a death claim even when the real bottleneck lies elsewhere — for example, missing nominee records, policy loan complications, old servicing mismatches, or legal-heir documentation.\nOnce the basic route is identified, the practical work usually involves reviewing available papers, mapping the insurer’s likely document expectations, identifying gaps, and helping the claimant understand what can realistically be resolved through nominee documentation, branch-level servicing, or a more formal entitlement route.\nIn many cases, the family’s biggest problem is not the absence of all documents but the absence of a clean file. Sahirasta helps organise the case, reduce confusion, and support follow-up so the insurer’s queries can be handled more systematically.\nWhere the matter is genuinely complex, Sahirasta helps the family understand the complication early instead of giving false comfort. That saves time, reduces wasted effort, and makes the next steps clearer.",
      "Documents Usually Required": "The exact list depends on the insurer, the policy, the claim amount, the nominee position, and whether the matter is straightforward or disputed. Commonly relevant documents include:\nOriginal policy bond, policy number, premium receipts, or insurer correspondence.\nDeath certificate of the policyholder.\nIdentity and address proof of the claimant.\nBank proof of the claimant, including cancelled cheque or account details where payout is to be credited.\nNominee proof, relationship proof, or legal-heir documents, depending on how the claim must be established.\nPAN, KYC, and other servicing documents where required by the insurer.\nAdditional overseas identification or attestation support where the claimant is an NRI.\nFamilies should not wait for a perfect file before seeking clarity. In many death-claim cases, the first useful step is to understand what type of claim it is and what missing documents actually matter.",
      "Why These Cases Get Stuck or Delayed": "Death claims often slow down because families assume the existence of a policy automatically means an immediate payout. In reality, delays usually arise from entitlement questions, incomplete servicing records, mismatch in claimant details, missing policy papers, unclear nominee status, or insurer queries that are not answered in time.\nIn older policies, the problem may be buried in legacy records — a policy loan, an assignment, a change that was never properly updated, or a missing trail showing whether the policy was in force at the relevant time.\nSome cases also become harder because different family members hold different pieces of the puzzle. One person has the bond, another knows the premium history, another holds the death certificate, and nobody has a complete picture. That fragmentation causes avoidable delay.",
      "Special Notes for Widows, Legal Heirs, and NRIs": "Widows and immediate family members are often pushed into claim handling at a time when they are least prepared for bureaucratic complexity. A calm, structured review helps separate what is emotionally heavy from what is procedurally required.\nWhere there is no clear nominee route, the case may shift into legal-heir or succession territory. That does not make the claim impossible, but it does change the proof and process needed.\nNRIs often face additional difficulty because the policy and insurer records are in India while the claimant is abroad. Remote handling is still possible in many cases, but documentation and follow-up need to be better organised, not looser.",
      "Frequently Asked Questions": "Can a widow make the claim even if she is not sure whether she is the recorded nominee?\nPossibly, yes — but the first step is to establish what the insurer’s records show and whether the case can proceed through nominee status, legal-heir proof, or another entitlement route.\nWhat if the original policy bond is missing?\nThe claim may still be possible. Missing bonds create more work, but other records may help reconstruct the case and identify what the insurer will require.\nWhat if multiple family members are involved?\nThat is common. The key is to understand who is entitled to act, what documents support that position, and whether the insurer is likely to require additional family or succession documentation.\nCan an NRI pursue a death claim on an Indian policy?\nYes. Extra documentation may be required, but many cases can still be reviewed and progressed through a structured remote process.\nWhat if the insurer has already asked for documents and the case still is not moving?\nThat usually means the issue is not only submission but clarity. A careful review can help identify whether the real obstacle is entitlement, record mismatch, policy status, or incomplete follow-up.",
      "Final Call to Action": "If your family is trying to deal with an insurance claim after a death and the process feels unclear, slow, or harder than it should be, do not keep guessing your way through it.\nWhether you have a clear nominee record or only partial papers, Sahirasta can review the case and help you understand the likely path, the missing pieces, and the next practical steps.\nRequest a Case Review"
    },
    "slug": "insurance-death-claim-support"
  },
  {
    "num": 3,
    "title": "Rejected Claims",
    "sections": {
      "Hero Section": "Page headline: Get Help Reviewing and Challenging Rejected Insurance Claims\nSubheadline: When an insurer has declined a claim and the rejection does not make sense, Sahirasta helps you understand the stated reason, review the file, and identify the next practical route.\nSupport line: We assist policyholders, widows, legal heirs, families, senior citizens, and NRIs dealing with rejection letters, disputed documents, legacy records, and unclear insurer communication.\nPrimary CTA: Request a Case Review\nSecondary CTA: See Documents Usually Required",
      "What Is This Service?": "This service is for cases where an insurer has rejected a claim and the claimant needs a structured review of what actually happened. Sometimes the rejection is based on missing papers, delayed intimation, policy-status questions, alleged non-disclosure, nominee confusion, or a mismatch between what the family believes and what the insurer’s records show.\nA rejection letter often sounds final, but it is not always the end of the matter. Some rejections are based on curable defects. Some rest on incomplete or misunderstood facts. Some require escalation, clarification, fresh representation, or a cleaner documentary file before the next step becomes visible.\nThis page is not about giving false hope. It is about separating valid rejection from questionable rejection, and helping the claimant understand whether the issue is document repair, record clarification, entitlement proof, policy-status review, or a larger dispute.",
      "When Does This Issue Usually Arise?": "The insurer has issued a formal rejection letter after a death claim, maturity claim, survival benefit claim, or other policy-related claim.\nThe family was told orally that the claim cannot be processed, but the exact reason remains vague or keeps shifting.\nThe rejection mentions non-disclosure, policy lapse, exclusion, delay, missing documents, or defective proof, but the claimant is not sure whether that position is correct.\nThe insurer relies on old servicing records, medical history, or policy terms that the claimant has never properly seen or understood.\nA widow, child, or legal heir receives a rejection after submitting the claim and does not know whether the matter should be accepted, corrected, or challenged.",
      "Who Typically Needs Help With This?": "Claimants who have received a written rejection and need help understanding whether it can be questioned or cured.\nWidows, widowers, sons, daughters, and other family members handling a rejected death claim after the policyholder’s death.\nPolicyholders whose maturity, survival, or servicing-linked claims have been declined on technical grounds.\nNRIs dealing with Indian insurance claim rejections remotely and trying to assess the realistic path forward.\nFamilies with partial records who do not know whether the insurer’s stated reason is the real issue or only part of the problem.",
      "How Sahirasta Helps": "Sahirasta begins by reading the rejection as a working document rather than as a verdict carved in stone. The first task is to understand exactly what the insurer has said, what documents were submitted, what facts may be missing from the file, and whether the case is being described correctly in the first place.\nIn some cases, the rejection turns on a practical defect that can still be addressed: missing claimant proof, nominee mismatch, incomplete discharge paperwork, absent bank records, or confusion over who is entitled to proceed. In other cases, the issue is more serious and requires a closer review of policy history, underwriting questions, disclosure allegations, servicing records, or the insurer’s interpretation of events.\nSahirasta helps organise the papers, identify the probable weak points, separate emotional reaction from documentary reality, and move the matter toward the next sensible step. That may mean fresh representation, better documentation, structured follow-up, or escalation. The goal is not noise. The goal is clarity and an informed route.\nWhere the rejection appears fundamentally difficult to dislodge, Sahirasta helps the claimant understand that early as well. Clear bad news is better than endless confusion.",
      "Documents Usually Required": "The exact document set depends on the claim type, the insurer, and the reason given for rejection. Commonly relevant documents include:\nThe rejection letter, email, or any written communication from the insurer explaining why the claim was declined.\nOriginal claim papers already submitted, including claim forms, discharge papers, and supporting records where available.\nPolicy bond, policy number, premium receipts, servicing correspondence, and any policy-status records available with the claimant.\nIdentity, address, PAN, and bank proof of the claimant.\nDeath certificate, hospital records, medical papers, nominee proof, legal-heir documents, or relationship proof where the rejected claim arises after death.\nAny additional letters, deficiency memos, branch communications, or complaint records that show how the matter progressed before rejection.\nIt is useful to gather the entire communication trail, not just the final rejection letter. The path into rejection often reveals more than the rejection itself.",
      "Why These Cases Get Rejected or Stay Rejected": "Insurance claims are not rejected for only one reason. Some fail because important facts were never properly documented. Some run into policy-status problems. Some involve nominee or entitlement confusion. Some turn on medical or disclosure allegations. Others are weakened by delay, poor record-keeping, or fragmented family handling.\nA second problem begins after rejection: many claimants do not know what part of the rejection is factual, what part is procedural, and what part may be challengeable. Families often keep resubmitting scattered papers without addressing the actual point the insurer is relying on. That wastes time and hardens the file.\nOlder policies create their own complications. Branch records may be incomplete, servicing history may be unclear, the original proposer may no longer be alive to explain facts, and different family members may each hold only part of the paper trail. A rejection that looks simple on one page can hide a much messier underlying record.",
      "Special Notes for Widows, Legal Heirs, and NRIs": "Rejected claims are especially difficult for widows and families because the rejection often arrives after they believed the hardest part was already over. By that stage they may have submitted documents, waited for months, and emotionally assumed the claim would be processed. A disciplined review helps restore clarity.\nWhere nominee status is weak, absent, disputed, or outdated, the rejection may partly reflect an entitlement issue rather than the full merits of the underlying policy. That changes what has to be fixed first.\nNRIs often face a disadvantage because communication is fragmented across branch offices, email threads, family members, and old Indian records. Distance does not make the case impossible, but it makes orderly documentation far more important.\nIn all three situations, incomplete papers do not automatically end the matter. They simply make it more important to identify the real reason the insurer has relied on and the best available response.",
      "Frequently Asked Questions": "Does a rejection letter always mean the claim is over?\nNo. Some rejections are effectively final, but others depend on defects that may still be reviewed, clarified, or challenged. The first step is to understand what kind of rejection it is.\nWhat if the insurer has rejected the claim but has not explained the reason clearly?\nThat is itself a problem worth examining. Vague or shifting explanations make it harder for the claimant to know what must actually be answered.\nCan a widow or family member pursue the matter after rejection?\nYes, in many cases. But the right route depends on whether the issue is entitlement, documentation, policy status, or a broader dispute over the insurer’s position.\nCan an NRI review and pursue a rejected Indian insurance claim?\nYes. The case may still move forward remotely, but the records and communication trail need to be assembled carefully.\nWhat if I suspect the rejection is unfair but I do not know how strong my case is?\nThat is exactly the stage where a realistic review helps. The goal is to understand the file before energy is wasted on the wrong response.",
      "Final Call to Action": "A rejected insurance claim should not be treated as a mystery, but it should not be accepted blindly either. The real question is whether the rejection reflects a fatal problem, a curable gap, or a position that needs to be examined more carefully.\nIf you have received a rejection letter, conflicting explanations, or a refusal that does not seem fully justified, Sahirasta can review the case and help you understand the next practical step.\nRequest a Case Review"
    },
    "slug": "insurance-rejected-claims"
  },
  {
    "num": 4,
    "title": "Short-Settled Claims",
    "sections": {
      "Hero Section": "Page headline: Get Help Reviewing Insurance Payouts That Seem Lower Than They Should Be\nSubheadline: When an insurer has paid an amount but the final settlement does not make sense, Sahirasta helps review the payout, identify the likely reason for the shortfall, and decide whether the matter should be clarified, corrected, or challenged.\nSupport line: We assist policyholders, widows, legal heirs, families, senior citizens, and NRIs who received an insurance payout but are not confident that the credited amount is correct.\nPrimary CTA: Request a Case Review\nSecondary CTA: See Documents Usually Required",
      "What Is This Service?": "This service is for cases where the insurer has already paid money, but the amount appears lower than expected and the claimant does not understand whether the difference is valid or not.\nA short-settlement problem usually begins after the credit comes in. The policyholder or family expected one amount, but the settlement advice, bank credit, or insurer explanation shows a lower figure. Sometimes there are deductions for policy loans, unpaid premiums, paid-up treatment, bonus differences, or rider-related limits. Sometimes the amount is simply not explained properly.\nThe real task is not to argue emotionally that the payout feels low. The real task is to examine the settlement line by line and work out whether the lower figure is contractually correct, poorly explained, or genuinely wrong.",
      "When Does This Issue Usually Arise?": "A maturity amount is credited, but the policyholder believes the final amount should have been higher.\nA survival benefit or money-back payment is received with deductions that were never clearly explained.\nA death claim is paid, but the widow, children, or family members suspect that the insurer settled for less than what was due.\nThe insurer shares a settlement figure without a calculation sheet that makes the result easy to understand.\nAn old policy loan, unpaid premium history, reduced paid-up status, or bonus misunderstanding surfaces only at the stage of settlement.\nThe claimant has compared the payout with policy expectations, branch assurances, or older illustrations and cannot reconcile the difference.",
      "Who Typically Needs Help With This?": "Policyholders who received maturity, surrender, or survival-benefit proceeds and are unsure whether the final amount is correct.\nWidows, widowers, legal heirs, and families reviewing a death-claim settlement that appears lower than expected.\nSenior citizens dealing with older LIC or insurer policies where bonus, paid-up status, or loan deductions were never clearly understood.\nNRIs and remote families who cannot keep visiting the branch or insurer repeatedly just to decode the settlement number.\nClients who were told a broad expected amount over the years and are now facing a final payout that does not match that expectation.",
      "How Sahirasta Helps": "Sahirasta begins by treating the settlement as a calculation problem, not just a complaint. The first step is to gather the policy papers, settlement advice, payout records, and any insurer communication that explains how the final amount was arrived at.\nThe next task is to separate expectation from contract. Many people remember what they were once told the policy would yield, but that may not reflect policy loans, missed premiums, reduced paid-up status, bonus treatment, rider conditions, or the actual benefit structure that applies at settlement.\nWhere the numbers still do not align, Sahirasta helps organise the case properly: identify the likely deduction points, request clearer explanation or calculation from the insurer, and present the matter as a specific payout-review issue instead of a vague protest.\nWhere the insurer’s calculation appears contractually justified, Sahirasta helps the client understand that as well. The aim is to avoid fighting shadows and focus only on disputes that have a real documentary basis.",
      "Documents Usually Required": "The exact document set depends on whether the payout relates to maturity, survival benefit, surrender, or death claim, but commonly relevant documents include:\nPolicy bond, policy schedule, policy number details, and any available policy terms or benefit illustration.\nSettlement letter, discharge voucher, payout advice, or any written communication showing the amount settled by the insurer.\nBank credit proof showing the actual amount received.\nPremium receipts, premium history, revival papers, loan statement, rider details, and servicing correspondence where relevant.\nIdentity, address, PAN, bank proof, and claimant entitlement documents if the payout followed the policyholder’s death.\nAny emails, branch letters, notes, or screenshots showing what explanation the insurer gave for the settlement figure.",
      "Why These Cases Get Short-Settled or Appear Short-Settled": "Some payouts are lower because the policy had an outstanding loan and accumulated loan interest which the claimant had forgotten or never tracked carefully.\nSome policies have slipped into paid-up or reduced-benefit status after irregular premiums, so the final benefit is lower than the original full-term expectation.\nIn many cases, the confusion arises because people remember a projected or bonus-influenced figure as if it were guaranteed. When the actual payout differs, it feels like a short-settlement even where part of the difference is contractual.\nOther disputes arise because the insurer’s settlement note is vague, the calculation is not shared properly, rider treatment is not explained, or a clerical or servicing error has not been ruled out.\nA family may also discover the problem only after a death claim is paid, when they compare the final credit with what they believed the policy amount to be.",
      "Special Notes for Widows, Legal Heirs, and NRIs": "These cases are especially difficult for widows and families because some money has already been paid. That creates pressure to accept the settlement quietly, even when the amount still does not make sense.\nWhere the payout follows a death claim, the family may be reviewing both entitlement documents and the insurer’s settlement figure at the same time. That can make it harder to see whether the real issue is claimant status, policy condition, deduction logic, or simple lack of explanation.\nNRIs often face an additional disadvantage because the policy papers, premium history, and insurer communications may be split across India-based family members, old records, and branch interactions that were never documented cleanly.\nA lower-than-expected payout is not automatically wrong. But it should not be accepted blindly either. The first job is to understand the numbers before deciding whether correction or challenge is worthwhile.",
      "Frequently Asked Questions": "Can an insurance payout be questioned if the insurer has already credited some amount?\nYes. Payment does not automatically end the matter if the settlement figure appears inconsistent, unexplained, or lower than what the policy terms and history support.\nWhat if the insurer deducted a policy loan or interest from the payout?\nThat may be valid, but the deduction should still be reviewed properly. The question is whether the deduction is correctly calculated and adequately explained.\nWhat if the amount I expected was based on what someone told me years ago?\nThat happens often. The review must separate old expectations, branch-level statements, or memory-based assumptions from what the policy contract and servicing record actually support.\nCan widows or legal heirs question a death-claim payout that already came into the bank account?\nYes. But the strength of the case depends on the policy record, settlement explanation, and whether the issue is a genuine underpayment or a misunderstanding about benefit structure.\nCan NRIs review an Indian insurance settlement remotely?\nYes. Many cases can still be reviewed remotely, though coordination may take longer when documents and communications are split across countries and family members.",
      "Final Call to Action": "If an insurance payout has already been made but the amount still does not make sense, the next step is not guesswork. It is a structured review of what was paid, why it was paid, and whether the figure actually holds up.\nIf you received a maturity amount, survival benefit, or death-claim settlement that appears short, unclear, or poorly explained, Sahirasta can review the case and help you decide whether the payout should be accepted, clarified, or challenged.\nRequest a Case Review"
    },
    "slug": "insurance-short-settled-claims"
  },
  {
    "num": 5,
    "title": "Lost Policy Bond",
    "sections": {
      "Hero Section": "Page headline: Lost Your Policy Bond? We Help You Move the Claim or Service Process Forward\nSubheadline: A missing policy bond can delay maturity, surrender, loan, correction, or death-claim work. Sahirasta helps you identify the right duplicate-document route and organise the case properly.\nPrimary CTA: Request a Case Review\nSupport line: For policyholders, widows, legal heirs, NRIs, and families dealing with old LIC or insurance records.",
      "What This Service Is": "A lost policy bond does not always mean the underlying insurance policy is lost. In many cases, the policy still exists in the insurer’s records, but the original bond is missing, damaged, misplaced, or unavailable when the client finally needs to act. The problem usually becomes urgent only when someone tries to claim maturity proceeds, submit a death claim, apply for a policy loan, surrender the policy, or correct older records and is told that the original bond is not readily available.\nThis service focuses on helping the client move from panic to process. Sahirasta helps identify whether the insurer will need a duplicate policy bond, a lost-policy declaration, an indemnity-based route, or some other servicing step depending on the type of request and the insurer’s requirements. The aim is not to dramatise the missing paper, but to restore documentary control so the real financial issue can move forward.",
      "When This Issue Usually Arises": "The problem often surfaces after many years of inactivity, when the policyholder has shifted home, changed family circumstances, or simply not handled the policy file for a long time.\nIt also arises after the death of the policyholder, when widows, children, or other legal heirs discover that the family knows the insurer’s name or policy number but cannot find the original bond in the documents left behind.\nIn some cases the bond is not exactly lost, but damaged, partially illegible, or held by another family member, branch, or intermediary. In others, the client is unsure whether the bond was ever received, whether it was submitted earlier for some servicing step, or whether the policy is now in a form where the insurer can process the case without the original bond after additional paperwork.",
      "Who Typically Needs Help With This?": "Policyholders nearing maturity who need to submit documents but cannot locate the bond.\nFamilies and legal heirs handling a death claim where the policy papers are incomplete or scattered.\nSenior citizens dealing with very old LIC or insurer policies kept in paper files for decades.\nClients trying to surrender a policy, take a loan, or correct records after years of not engaging with the policy.\nNRIs and remote families who know that a policy exists but do not have direct physical access to the original documents in India.",
      "How Sahirasta Helps": "Sahirasta begins by identifying the real objective behind the missing bond. The question is not only whether the paper is lost, but what the client is actually trying to do: claim maturity, pursue a death claim, seek a policy loan, surrender the policy, correct records, or revive communication with the insurer. That distinction matters because insurers may not ask for the same replacement route in every situation.\nThe next step is to gather whatever evidence still exists: policy number, premium receipts, branch correspondence, old SMS or email alerts, bank entries, servicing letters, or any partial copy of the bond. Even incomplete evidence can help establish the policy trail and reduce guesswork. Sahirasta then helps organise the case so that the insurer sees a coherent request rather than a confused explanation that keeps bouncing between desks.\nWhere a duplicate bond or lost-policy declaration is required, the case must usually be supported with identity proof, policy particulars, claimant details, and any indemnity or declaration documents the insurer asks for. Sahirasta helps the client understand this stage clearly and prepares the file so the missing document does not keep blocking the real financial outcome.\nIf the issue is part of a larger death-claim or servicing problem, Sahirasta also helps separate the bond problem from the entitlement problem. Families often lose time because they are trying to solve every issue at once. A cleaner approach is to identify which missing paper can be replaced, which entitlement documents are still needed, and what the insurer is likely to insist on before moving the claim or service request.",
      "Documents Usually Required": "The exact requirements vary by insurer and the underlying service requested, but commonly relevant documents include:\nPolicy number and whatever policy details are available, including insurer name, branch, premium mode, or approximate commencement date.\nAny photocopy, scanned copy, image, schedule page, premium receipt, ECS record, bank entry, or servicing communication linked to the policy.\nIdentity and address proof of the policyholder or claimant.\nPAN, bank proof, and contact details where the next servicing step involves payment or proceeds.\nDeath certificate, nominee documents, legal-heir documents, or relationship proof where the policyholder has died.\nInsurer-prescribed declaration, indemnity, or duplicate-bond request forms where applicable.\nAny letters, emails, branch responses, or screenshots showing that the insurer has already indicated what is missing.",
      "Why These Cases Get Stuck When the Policy Bond Is Missing": "Many clients assume the missing bond is a small paperwork issue and approach the branch without a structured file. The result is repeated visits, inconsistent guidance, and requests for fresh documents each time.\nIn older policies, the contact details, signature, nominee details, or bank account linked to the policy may also be outdated. That means the lost bond is only one part of the blockage.\nSome families do not know the exact policy status. They may not know whether the policy matured already, lapsed, became paid-up, was assigned, or had a loan attached. Without clarity on status, the missing bond problem becomes harder to resolve.\nWhere the policyholder has died, the insurer may need to see both replacement-document steps and entitlement documents. These cases slow down further if family members are unclear about who should sign, who the nominee is, or whether succession documentation is required.",
      "Special Notes for Widows, Legal Heirs, and NRIs": "Widows and families often face this problem in emotionally difficult circumstances. They may know that a policy exists but feel paralysed because the original bond cannot be found. The right response is not to assume the claim is impossible, but to rebuild the document trail patiently and understand what the insurer will accept as the next step.\nNRIs face a different version of the same problem. The policy may be in India, the family may have partial papers, and branch communication may be fragmented. These cases can still move, but only if the records, claimant identity, and authority to act are organised properly from the start.\nA lost bond does not automatically destroy the claim. But it does increase the need for clean paperwork, correct declarations, and careful sequencing.",
      "Frequently Asked Questions": "Can a claim or policy service request move forward if the original policy bond is missing?\nOften yes, but the insurer may require a duplicate-bond request, declaration, indemnity, or other supporting process before proceeding.\nWhat if I only know the insurer name and have no policy bond?\nThat is still workable in some cases if other policy evidence exists, such as premium receipts, bank entries, SMS alerts, servicing letters, or old correspondence.\nCan a widow or family member handle this after the policyholder’s death?\nYes, but the missing-bond issue will usually need to be handled alongside nominee or legal-heir documentation, depending on the insurer’s record and claim stage.\nDoes losing the policy bond mean the money is gone?\nNo. The missing bond is a documentation problem, not proof that the policy benefit has vanished. The real question is how to re-establish the file correctly.\nCan NRIs address a lost policy-bond issue without repeated travel?\nMany cases can still be organised remotely, though paperwork and coordination may take longer when records are scattered across countries or family members.",
      "Final Call to Action": "If a missing policy bond is delaying maturity, surrender, correction, loan, or death-claim action, the next step is not panic. It is to identify what the insurer actually needs, what evidence still exists, and how to move the case in the right order.\nIf you cannot find the original policy bond and do not know how to proceed, Sahirasta can review the case and help you organise the replacement-document route properly.\nRequest a Case Review"
    },
    "slug": "insurance-lost-policy-bond"
  },
  {
    "num": 6,
    "title": "Nominee Issues",
    "sections": {
      "Hero Section": "Page headline: Nominee Problems Are Blocking the Insurance Claim? We Help Clarify the Route\nSubheadline: Insurance claims often get delayed because the nominee details are outdated, missing, disputed, or misunderstood. Sahirasta helps organise the entitlement position and move the case forward with the right supporting documents.\nPrimary CTA: Request a Case Review\nSupport line: For policyholders, widows, legal heirs, NRIs, and families handling old LIC or insurer records.",
      "What This Service Is": "A nominee issue is not always a simple clerical mistake. In some cases, there is no nominee recorded. In others, the nominee died earlier, the name on record does not match current ID documents, the family assumes the nominee is the final owner, or multiple relatives disagree about who should make the claim. The result is that the insurer does not get a clean entitlement file.\nThis service focuses on untangling that confusion. Sahirasta helps identify what kind of nominee problem exists, what the insurer is likely to ask for next, and whether the matter can proceed through a nominee route, a legal-heir route, or a broader succession-support route.",
      "When This Issue Usually Arises": "The problem usually surfaces after the death of the policyholder, when the family starts the claim process and discovers that the nomination details are old, incomplete, or practically unusable. A policy may still show a deceased nominee, a minor nominee without proper guardian details, or a nominee whose name does not match current records.\nIt also arises when a policyholder wants to update an old policy and realises that the nomination was never added, never changed after marriage or remarriage, or no longer reflects the present family situation. In some cases the family assumes that being the legal heir is enough, while the insurer first asks about the nomination on record.\nAnother common version is internal family confusion. One relative may have the bond, another may be named as nominee, and others may believe they also have rights in the proceeds. These cases become emotionally messy very quickly unless the paperwork is organised properly.",
      "Who Typically Needs Help With This?": "Widows, children, parents, or siblings trying to file a death claim where the nominee details are missing or problematic.\nFamilies dealing with old LIC or insurer policies where the nomination was never updated after major life events.\nClients facing mismatch between nominee name, relationship, age, or identity records.\nFamilies where the nominee is deceased, unreachable, unwilling to cooperate, or not the only interested party.\nNRIs and remote families handling nominee questions from outside India while documents remain scattered across relatives or old files.\nPolicyholders who want to correct the position before a future claim becomes more complicated.",
      "How Sahirasta Helps": "Sahirasta begins by separating the emotional dispute from the paperwork issue. The first question is what exactly the insurer’s records show: whether a nominee exists, whether that nominee is traceable and valid in practical terms, and whether the case can move on the basis of nomination alone or requires a broader entitlement file.\nThe next step is to gather the documents that establish the present position clearly. That may include the policy record, death certificate, identity and relationship proof, legal-heir documents where needed, and any prior correspondence that shows what the insurer has already asked for or objected to.\nWhere the nominee details are outdated or unusable, the case often turns into a documentation and sequencing problem rather than a purely legal one. Families lose time when they submit partial papers without a clear explanation of why the nominee route is not straightforward. Sahirasta helps organise the file so the insurer sees one coherent claim path instead of a bundle of disconnected documents.\nIn some cases the right route is straightforward. In others, the family may need succession proof, indemnities, declarations, guardian documents for a minor beneficiary, or additional internal clarifications. Sahirasta helps map that route before the family wastes time on repeated branch visits and contradictory advice.",
      "Documents Usually Required": "The exact document set depends on the insurer and the nature of the nominee issue, but commonly relevant documents include:\nPolicy number, policy schedule, bond, or any servicing communication showing the nominee details on record.\nDeath certificate of the policyholder where the issue arises in a death-claim context.\nIdentity, address, PAN, and bank proof of the nominee or claimant.\nRelationship proof and family documents where the insurer needs clarity on how the claimant relates to the policyholder.\nLegal-heir certificate, succession documents, affidavit, indemnity, or declaration where nomination alone does not resolve the entitlement question.\nDeath certificate of the nominee where the recorded nominee is no longer alive.\nGuardian documents where the nominee is or was a minor and representation is now required.\nAny branch letters, email trails, rejection notes, or document checklists already shared by the insurer.",
      "Why Nominee-Issue Cases Get Stuck": "Families often assume that the word nominee settles everything. In practice, nominee-related cases can stall because the nomination on the insurer’s record is missing, outdated, inconsistent with current identity documents, or no longer workable after death or family change.\nAnother common problem is that the family submits identity proof but does not explain the entitlement logic clearly. If the insurer cannot understand whether the claim is being made by the nominee, by legal heirs, or by a guardian or representative, the file keeps bouncing back for clarification.\nOlder policies create another layer of difficulty. The policyholder may have married, remarried, shifted cities, changed names in records, or never updated nomination at all. In such cases, the insurer may ask for additional proof before releasing any money.\nThese cases also get delayed because families disagree internally. One person may be coordinating, another may be named in the record, and others may challenge the route. Without a structured file, every round of communication becomes slower and more stressful.",
      "Special Notes for Widows, Legal Heirs, and NRIs": "Widows and children often face nominee issues at the worst possible time, when the death claim itself is emotionally heavy and the policy paperwork is scattered. A nomination problem does not automatically mean the money is lost, but it does mean the entitlement route needs to be explained properly.\nNRIs face an added burden because branch communication, notarisation, identity proof, and family coordination may happen across countries. These cases are still workable, but only if the documentation is arranged in the right order and the family is clear about who is claiming on what basis.\nIn some cases the nominee issue is only one part of a larger block involving a missing bond, outdated KYC, old address, policy loan, or insurer-record mismatch. The right strategy is to identify the primary blocker first and then sequence the rest properly.",
      "Frequently Asked Questions": "What if the policy has no nominee recorded?\nThe claim may still be possible, but the insurer will usually need a different entitlement route, often involving legal-heir or succession-related documents.\nWhat happens if the nominee recorded in the policy has already died?\nThe insurer will usually need supporting documents showing that the nominee is no longer alive and may then ask for the next valid entitlement route based on the case facts.\nDoes the nominee always become the final owner of the insurance money?\nNot every family dispute can be solved by quoting the nominee field alone. The practical route depends on the insurer’s process, the family situation, and the supporting documents available.\nCan Sahirasta help if the family itself is confused about who should claim?\nYes. Many cases first need the paperwork route clarified before the insurer can process anything sensibly.\nCan NRIs handle nominee-issue cases without repeated travel?\nMany cases can be organised remotely, though delays increase when documents are scattered across relatives, countries, or old insurer records.",
      "Final Call to Action": "If a policy claim is stuck because the nominee details are missing, outdated, disputed, or unclear, the next step is to organise the entitlement route properly. Guesswork only creates more delay.\nIf nominee confusion is blocking an insurance payout, Sahirasta can review the case and help identify the right document and claim path.\nRequest a Case Review"
    },
    "slug": "insurance-nominee-issues"
  },
  {
    "num": 7,
    "title": "Policy Loan Complications",
    "sections": {
      "Hero Section": "Page headline: Is an Old Policy Loan Reducing or Blocking the Insurance Payout?\nSubheadline: Insurance payouts often become confusing when an old policy loan, accumulated interest, assignment record, or branch clarification issue affects the net amount payable. Sahirasta helps review the records, explain the likely deduction trail, and organise the next steps.\nPrimary CTA: Request a Case Review\nSupport line: For policyholders, widows, legal heirs, NRIs, and families dealing with old LIC or insurer loan-linked policies.",
      "What This Service Is": "A policy loan complication is not just a question of whether a loan exists. The real difficulty begins when the client expects one amount, the insurer refers to another, and the payout becomes hard to understand because outstanding loan, interest, assignment history, or servicing gaps are affecting what is actually payable.\nThis service focuses on making that picture clear. Sahirasta helps identify whether the issue is mainly an old loan deduction, a loan-status mismatch, an incomplete reassignment, a branch-record problem, or a broader documentation gap that is stopping the insurer from releasing or correctly explaining the amount.\nMany families assume the insurer has made an arbitrary deduction. Sometimes the deduction is valid, sometimes the record is incomplete, and sometimes the case is stuck simply because nobody has reconciled the loan trail properly. The service is built to diagnose that difference before more time is lost.",
      "When This Issue Usually Arises": "The issue often surfaces at maturity, surrender, or death-claim stage, when the expected payout is lower than anticipated and the insurer says that an old policy loan or accumulated interest is being adjusted first.\nIt also arises when the policy had been assigned in connection with the loan and the reassignment position is unclear. A client may have repaid something years earlier, but the paperwork trail may not clearly show whether the policy was fully released back into the policyholder’s name.\nAnother common version is a record gap. The family may know that a loan was taken, but not know how much remained outstanding, what interest continued to run, whether any notices were issued, or how the branch is calculating the net payable amount today.",
      "Who Typically Needs Help With This?": "Policyholders trying to understand why the maturity, surrender, or loan value available under the policy is lower than expected.\nWidows, legal heirs, and family members who expected the full claim amount but were informed that an old policy loan or deduction is reducing the payout.\nClients dealing with older LIC or insurer policies where the loan history, assignment status, or servicing records are incomplete or difficult to trace.\nFamilies handling a death claim where the insurer is talking about loan adjustment, unpaid interest, or a policy assignment that nobody fully understood earlier.\nNRIs and remote families trying to assess an Indian insurance policy from outside the country while the original loan or branch history remains buried in old files.",
      "How Sahirasta Helps": "Sahirasta begins by separating the emotional reaction from the record problem. The first step is to identify what exactly the insurer is saying: whether there is a currently outstanding loan, whether the policy was assigned against that loan, whether interest has continued to accumulate, and whether the amount being withheld or reduced appears linked to a recognisable loan trail.\nThe next step is to gather the available documents and map the sequence. That may include the policy bond, loan letters, branch statements, assignment or reassignment papers, payout advice, and any communication already received from the insurer. Many cases become clearer only when the history is arranged in order instead of treated as isolated pieces.\nWhere the issue is mainly one of reconciliation, Sahirasta helps the client understand what the insurer may be deducting and why. Where the issue is broader — for example, a missing reassignment, old branch confusion, identity mismatch, or incomplete death-claim paperwork — the case may need coordinated cleanup before any meaningful payout clarification can happen.\nThe objective is not to promise a number blindly. The objective is to help the client understand the likely net-payable route, identify avoidable documentation gaps, and reduce the chance of the matter remaining stuck because no one has organised the record properly.",
      "Documents Usually Required": "The exact document set depends on the insurer and the age of the policy, but commonly relevant documents include:\nPolicy number, policy schedule, bond, premium receipts, or any other record identifying the policy clearly.\nLoan application, loan sanction letter, loan statement, branch correspondence, repayment record, or any other paper showing the loan history.\nAssignment or reassignment documents where the policy was linked to a lender or branch-controlled loan arrangement.\nMaturity intimation, surrender value communication, claim letter, or payout advice showing the deduction or reduced amount payable.\nIdentity, PAN, address proof, and bank proof of the policyholder, nominee, or claimant.\nDeath certificate and claimant entitlement documents where the issue arises in a death-claim context.\nAny email trails, SMS alerts, branch notes, or servicing letters already shared by the insurer.",
      "Why Policy-Loan Cases Get Stuck": "These cases often stall because the client and the insurer are not looking at the same number. Families focus on the gross policy value, while the insurer is calculating the net amount after adjusting loan, interest, assignment-related obligations, or other linked deductions. If nobody explains that gap clearly, the case feels arbitrary even when a document trail exists.\nAnother common problem is missing history. The loan may have been taken long ago, papers may be scattered, and branch staff may no longer have the older context at hand. Where reassignment was not completed cleanly, or where the claimant cannot show what was repaid and when, the payout conversation slows down quickly.\nOlder policies also create interpretation problems. The policyholder may have shifted addresses, changed names, died, or left records incomplete. By the time a maturity or death claim is made, the policy loan issue may be tangled together with nominee questions, missing bond issues, record mismatch, or KYC problems.\nSome cases get delayed simply because the family assumes the insurer’s deduction cannot be checked. In reality, the position may still be understood better, but only if the documents are reviewed calmly and the case is handled as a reconciliation problem instead of a general complaint.",
      "Special Notes for Widows, Legal Heirs, and NRIs": "Widows and children often encounter policy-loan complications only after the policyholder’s death, when the branch says that the amount payable will be lower because of an old loan or interest adjustment. That can be especially distressing when the family never handled the loan earlier and has no immediate access to the papers.\nLegal heirs may also face confusion where the original policyholder borrowed against the policy, kept partial records, and never clearly explained the status to the rest of the family. In such cases the death claim and the loan clarification move together, and the entitlement route has to be organised carefully.\nNRIs face an added burden because they may need to reconstruct the case remotely while the branch history, assignment papers, or family records remain in India. These cases are still workable, but they require tighter coordination and more careful document sequencing than standard servicing requests.\nIn some matters the policy-loan issue is not isolated. It may sit alongside a lost bond, nominee problem, address mismatch, or unresolved insurer-record issue. The right strategy is therefore to identify the full block, not just the visible loan deduction.",
      "Frequently Asked Questions": "Can a policy loan reduce the final insurance payout?\nYes. Depending on the stage of the policy and the insurer’s records, outstanding loan, accumulated interest, or related adjustments can reduce what is finally payable.\nWhat if the family did not know that a loan had been taken?\nThat is common in older policies. The first step is to identify what the insurer’s records show and whether the loan trail can be reconstructed from branch statements, old papers, or servicing communications.\nDoes repayment automatically remove all future deduction issues?\nNot always. If the reassignment or record update was not completed properly, confusion can continue even after some repayment happened earlier.\nCan Sahirasta tell us whether the insurer’s deduction appears understandable?\nSahirasta can help review the available material, organise the record trail, and identify whether the case looks like a routine loan adjustment, a record mismatch, or a broader documentation problem that needs further clarification.\nCan NRIs handle policy-loan complications without repeated travel?\nMany cases can be organised remotely, though older loan-linked policies usually require stronger document coordination and careful follow-up.",
      "Final Call to Action": "If an old policy loan, unexplained deduction, or assignment issue is reducing or delaying the insurance payout, the next step is to review the file before making assumptions about what is or is not payable.\nIf a policy loan complication is blocking clarity on the amount receivable, Sahirasta can review the case and help identify the right documentation and payout route.\nRequest a Case Review"
    },
    "slug": "insurance-policy-loan-complications"
  },
  {
    "num": 8,
    "title": "Old LIC / Insurer Record Mismatch",
    "sections": {
      "Hero Section": "Page headline: Old LIC or Insurer Record Mismatch? We Help Untangle the File and Move It Forward\nSubheadline: When names, dates, policy details, branch records, or payout history do not match across old insurance records, Sahirasta helps identify the likely mismatch, organise the supporting papers, and structure the next steps.\nPrimary CTA: Request a Case Review\nSupport line: For policyholders, widows, legal heirs, NRIs, and families dealing with old LIC or insurer records that do not align.",
      "What This Service Is": "An insurer-record mismatch case arises when the policy papers, insurer system, claimant documents, or branch records do not line up cleanly. The problem may involve name spelling differences, changed surname after marriage, different initials, inconsistent dates of birth, old addresses, old bank details, nominee record gaps, policy-status confusion, or legacy branch entries that do not match the papers now being submitted.\nThese cases are especially common in older LIC and insurer files because the policy may have moved through multiple servicing stages over many years - manual records, branch transfers, migration to newer systems, family changes, and incomplete updates. By the time a maturity claim, death claim, survival benefit, or servicing request is made, one part of the record may say one thing and another part may say something else.\nThis service focuses on identifying what exactly does not match, why that mismatch matters to the insurer, and what route may be needed to correct, explain, or reconcile the file. The goal is not vague follow-up. The goal is to turn a confusing record problem into a structured documentation problem that can actually be worked.",
      "When This Issue Usually Arises": "A maturity, death claim, survival benefit, surrender, or servicing request is delayed because the insurer says the records do not match the documents submitted.\nThe policyholder's name appears differently across the policy bond, PAN, Aadhaar, bank records, marriage-related documents, or insurer database.\nThe date of birth, address, signature, or contact details in the insurer's old record do not match the current identity documents.\nA policy was serviced through an old branch, transferred to another office, or migrated from older records, and the current file history is incomplete or inconsistent.\nThe family is told that nominee details, claimant relationship details, or other core records do not align with what the insurer has on file.\nAn old payout, policy loan, assignment, or servicing remark appears in insurer records but is not clearly reflected in the papers available with the family.\nThe client has some policy documents, but the insurer system reflects a status, endorsement, or history that nobody is able to explain properly.",
      "Who Typically Needs Help With This?": "Policyholders whose old LIC or insurer policies are stuck because personal details in the record no longer match current documents.\nWidows, children, nominees, and legal heirs trying to pursue a claim where the insurer says that the old policy record is inconsistent or incomplete.\nFamilies handling older policies after a death and discovering that names, dates, nominee records, or branch history do not align cleanly.\nNRIs trying to manage Indian insurance matters remotely where the insurer's legacy records are difficult to verify from abroad.\nClients who have been told informally to 'correct the record first' but have never received a clear explanation of what exactly is wrong.",
      "How Sahirasta Helps": "Sahirasta begins by identifying the mismatch precisely. That step matters because 'record mismatch' is often used loosely. The actual issue may be a simple spelling variation, a name-change issue after marriage, an old address problem, a date-of-birth inconsistency, a branch-level record gap, an unupdated nominee trail, or a larger file-history problem involving multiple older entries.\nOnce the likely mismatch is identified, Sahirasta helps organise the papers into a coherent sequence so the problem can be explained instead of guessed. In many cases, the documents exist but are scattered and disconnected. One paper proves identity, another shows the old policy record, another explains the family relationship, and another helps reconcile the old and current details. Unless these are arranged properly, the insurer's objections keep repeating.\nWhere the matter overlaps with death claim, nominee issue, unpaid survival benefit, lost policy bond, or policy-loan complications, Sahirasta helps separate the issues so the file is not treated as one shapeless old-policy problem. That separation often makes the next step much clearer.",
      "Documents Usually Required": "The exact documents depend on the nature of the mismatch and the insurer involved, but commonly relevant papers include:\nPolicy bond, policy number, premium receipts, policy schedule, endorsement pages, and any old insurer or branch communication.\nPAN, Aadhaar, passport, bank proof, address proof, and any other identity documents showing the current record clearly.\nOlder identity or address proofs where they help connect the present details with the historical policy record.\nMarriage certificate, gazette publication, affidavit, name-change support, or relationship documents where surname or identity details changed over time.\nDeath certificate, nominee papers, legal-heir documents, succession-related papers, or claimant-relationship documents where the policyholder is deceased.\nBank statements, old cheque trail, or payout communication where the mismatch affects whether an amount was paid or who received it.\nAny insurer letters, emails, SMS alerts, branch notes, or objection memos showing what discrepancy the insurer has already flagged.",
      "Why These Cases Get Stuck": "Old-record mismatch matters drag on because the insurer usually wants consistency before moving money or servicing rights. If the name on the bond does not match the bank record, if the claimant's relationship is unclear on the face of the file, or if the policy history appears incomplete, the insurer will often slow the matter rather than take a clean decision quickly.\nAnother problem is that families often treat the issue as if one missing document will solve everything. In reality, the difficulty may be cumulative: part identity issue, part old branch-history issue, part nominee or entitlement confusion. Unless the mismatch is classified properly, repeated submissions only create more delay and more contradictory responses.\nThese cases also become harder with time. Records get older, branch staff change, papers go missing, and family memory becomes unreliable. What should have been a small clarification years earlier can become a full reconstruction exercise later.",
      "Special Notes for Widows, Legal Heirs, and NRIs": "Widows and family members often encounter insurer-record mismatch only after the policyholder's death, when the branch or claims desk starts pointing out name differences, old nominee gaps, address history problems, or document inconsistencies that were never resolved during the policyholder's lifetime.\nLegal heirs may face additional difficulty where the insurer is not only checking the claimant's entitlement but also trying to reconcile the policyholder's historical record. In such matters, the entitlement question and the record-correction question may move together, which is why the file has to be organised with more care than a simple servicing request.\nNRIs face an obvious coordination burden because the policy papers, family documents, older bank trail, and branch-level history may all remain in India while the person handling the matter is abroad. These cases can still be worked, but only with disciplined document sequencing and realistic expectations about old-record cleanup.",
      "Frequently Asked Questions": "What is an insurer-record mismatch in an insurance case?\nIt means the insurer's records do not align cleanly with the policy papers, identity documents, claimant documents, or servicing history now being relied on.\nWhat if the policyholder's name is spelled differently across documents?\nThat is common in older files. The key is not panic but proof - the records have to be connected through supporting documents so the insurer can see that the file still relates to the same person.\nCan a widow or legal heir continue the case if the old policy record is inconsistent?\nOften yes, but the file usually needs both entitlement documents and record-reconciliation documents. The insurer may not treat those as separate issues unless the case is structured properly.\nWhat if the branch says the old record is not traceable or not clear?\nThat does happen in older LIC and insurer matters. The practical route is usually to build the case from the available bond, policy number, receipts, claimant documents, and whatever historical communication still exists.\nCan NRIs handle old-record mismatch cases remotely?\nMany can, though older files often need stronger coordination, clearer documentation, and more patience than standard policy servicing matters.",
      "Final Call to Action": "If an insurance case is being delayed because the old LIC or insurer record does not match the documents now being produced, vague follow-up rarely fixes it. The mismatch has to be identified, explained, and supported properly.\nWhether the problem involves name differences, old branch records, identity mismatch, nominee confusion, or legacy data gaps, Sahirasta can review the file and help identify the likely route to move the matter forward.\nRequest a Case Review"
    },
    "slug": "insurance-old-record-mismatch"
  },
  {
    "num": 9,
    "title": "Survival Benefit Not Received",
    "sections": {
      "Hero Section": "Page headline: Survival Benefit Not Received? We Help Trace and Move the Case Forward\nSubheadline: If a money-back instalment or survival benefit under an insurance policy fell due but never reached you, Sahirasta helps review the records, identify the likely blockage, and organise the next steps.\nPrimary CTA: Request a Case Review\nSupport line: For policyholders, widows, legal heirs, NRIs, and families dealing with old LIC or insurer money-back policies.",
      "What This Service Is": "A survival-benefit issue arises when a scheduled payout under a money-back or similar policy became due, but the amount was never actually received by the policyholder. Unlike a final maturity claim, this problem concerns an intermediate payout that should have been released during the life of the policy and not only at the end of the term.\nThese cases are often more confusing than they sound. The family may know that the policy was supposed to pay something after a certain number of years, but may not know whether that instalment was processed, returned, held back for want of updated records, or never completed because the insurer’s servicing file was outdated. Sometimes the policyholder assumed the amount was small and would come automatically. Sometimes the cheque or credit failed and nobody followed up properly.\nThis service focuses on tracing that missed payout, distinguishing it from maturity and death-claim issues, and helping the client understand whether the real problem is non-receipt, policy status, bank/KYC mismatch, or old record friction.",
      "When This Issue Usually Arises": "The due date for a money-back instalment has passed, but no amount was ever credited to the policyholder’s bank account.\nThe insurer says a survival benefit was issued long ago, but the policyholder never received the cheque or cannot trace any bank credit.\nThe policyholder changed bank account, address, signature, contact number, or KYC details and the payout could not be completed properly.\nA family reviewing old policy papers realises that one or more periodic payouts may have become due before maturity, but there is no clear payment trail.\nThe policyholder later died, and the family is unsure whether an earlier survival benefit remained unpaid separately from any death claim or maturity-related amount.\nThe insurer’s records are old enough that nobody is clear whether the amount was paid, returned, kept pending, or blocked by a mismatch.",
      "Who Typically Needs Help With This?": "Policyholders holding money-back or similar policies where periodic benefits were supposed to be paid during the policy term.\nSenior citizens dealing with old LIC or insurer policies and trying to understand whether earlier payouts were ever received.\nWidows, children, or other family members sorting older insurance documents after a death and trying to identify unpaid amounts.\nNRIs handling Indian insurance policies remotely and trying to reconstruct whether a due survival benefit was missed.\nFamilies with only partial records such as a bond, policy number, premium trail, or old branch communication but no clear payout history.",
      "How Sahirasta Helps": "Sahirasta begins by identifying whether a survival benefit was actually due under the policy and on what basis. That sounds obvious, but many families mix up money-back instalments, maturity amounts, bonus expectations, and death-claim benefits as if they were all the same. They are not. The first job is to classify the amount correctly.\nThe next step is to examine whether the issue is true non-payment, failed payment, missing bank details, incomplete servicing compliance, or simple uncertainty because the payment trail was never preserved. In some cases the insurer may have attempted payment through cheque or older bank records. In others, the amount may still be unresolved because no updated discharge or banking documents were submitted when the instalment fell due.\nSahirasta helps organise the file, identify the likely blockage, and move the matter forward in a more disciplined way than scattered follow-up. Where the matter overlaps with nominee, death-claim, old-record mismatch, or missing-document problems, Sahirasta also helps separate those issues so the survival-benefit question does not remain buried under general confusion.",
      "Documents Usually Required": "The exact papers depend on the insurer, the age of the policy, and whether the policyholder is alive or represented by family. Commonly relevant documents include:\nPolicy bond, policy number, premium receipts, policy schedule, or any insurer communication showing the money-back or survival-benefit structure.\nIdentity, address, PAN, and bank proof of the policyholder or claimant.\nBank statements, cheque records, or any other payment trail that may help show whether the due amount was ever actually received.\nDischarge forms, servicing requests, or KYC updates where the insurer required these before release of the instalment.\nDeath certificate and entitlement documents where the policyholder is deceased and the family is now tracing the unpaid benefit.\nNominee, legal-heir, succession, relationship, or representative documents where the claimant route is not straightforward.\nOverseas identity and address support where the person handling the matter is an NRI.",
      "Why These Cases Get Stuck": "Survival-benefit cases often remain unresolved because the amount is neither dramatic enough to trigger urgent action nor obvious enough to track casually. A policyholder may miss a cheque, overlook a failed credit, or assume that the insurer will reprocess the amount automatically. That assumption is often wrong.\nAnother common problem is that old money-back policies sit in legacy servicing systems with outdated addresses, closed bank accounts, older signature records, or incomplete KYC. When the due instalment arises, the payout does not move cleanly, and years later nobody remembers what happened.\nThese matters also get confused with other insurance events. Families may think they are handling a maturity claim or a death claim when the unresolved issue is actually an earlier periodic benefit that fell due independently. Unless the timeline is reconstructed properly, the case stays muddy and the insurer’s responses remain fragmented.",
      "Special Notes for Widows, Legal Heirs, and NRIs": "Widows and family members often discover these issues only while sorting old papers after a death. The immediate question is usually not technical law but practical uncertainty: was a periodic benefit already paid, is it still traceable, and who should now pursue the matter if the original policyholder is no longer alive?\nWhere the policyholder died after a survival benefit had already fallen due, the family may need to distinguish between an unpaid instalment that belonged to the policyholder and a later death-claim or policy-status question. That distinction matters because the paperwork route may not be identical.\nNRIs face an added coordination burden because the policy records, old bank trail, and branch-level history may all remain in India while the person trying to understand the case is abroad. These matters are still workable, but only if the records are gathered patiently and the issue is defined correctly from the start.",
      "Frequently Asked Questions": "What is a survival benefit in an insurance policy?\nIn this context, it usually means a scheduled payout due during the policy term under a money-back or similar plan, rather than the final maturity amount at the end.\nWhat if I am not sure whether the survival benefit was ever paid?\nThat is common. The first step is to reconstruct the due date, check available bank or cheque trail, and compare it with the insurer’s records.\nCan a family pursue an unpaid survival benefit after the policyholder’s death?\nOften yes, but the route depends on whether the amount had already become due during the policyholder’s lifetime and how the claimant’s entitlement must now be established.\nWhat if I do not have the original policy bond?\nThe case may still be reviewed using other available records such as policy number, premium receipts, insurer letters, or claimant documents, though missing papers can slow the process.\nCan NRIs trace unpaid survival benefits on Indian policies?\nYes. Additional documentation and more careful coordination may be needed, but many such cases can still be handled through a structured remote process.",
      "Final Call to Action": "If a survival benefit under a money-back policy fell due but never reached the right person, leaving the file untouched rarely improves anything. Bank details go stale, records get harder to trace, and family memory fades.\nWhether you have a complete file or only scattered policy papers, Sahirasta can review the case and help identify the likely route to clarify or recover the unpaid survival benefit.\nRequest a Case Review"
    },
    "slug": "insurance-survival-benefit-not-received"
  },
  {
    "num": 10,
    "title": "Address / KYC / Bank Mismatch Blocking Payout",
    "sections": {
      "Hero Section": "Page headline: Insurance Payout Stuck Because Records Do Not Match? We Help Clean Up the File\nSubheadline: When an insurance amount is due but cannot be released because bank details, KYC, address, PAN, or claimant records do not align, Sahirasta helps identify the real blockage, organise the corrective papers, and move the payout route forward.\nPrimary CTA: Request a Case Review\nSupport line: For policyholders, widows, legal heirs, NRIs, senior citizens, and families facing payout blockage on old LIC or insurer policies.",
      "What This Service Is": "This service is for cases where the policy money may be payable, but the insurer is unable or unwilling to release it because the servicing record, payout route, or claimant details are not in a condition the insurer considers clean enough for release. The visible objection may mention bank mismatch, incomplete KYC, old address, PAN issue, failed credit, or record inconsistency. The real problem is that the payout path is not aligned properly.\nThese matters are different from a classic claim rejection. The insurer may not be denying that money is due at all. Instead, the case remains stuck because the amount cannot be safely or correctly released on the basis of the records currently available. That is why repeated submission of one new cheque leaf or one updated ID proof often does not solve the full problem.\nThis service focuses on identifying the full mismatch set, not just the first objection. In many older insurance files, the bank route, address history, PAN trail, claimant identity, and policy-servicing record have drifted apart over time. Unless those strands are brought back into one coherent file, payout release keeps getting delayed.",
      "When This Issue Usually Arises": "A maturity amount, survival benefit, or other policy payout is due, but the insurer says the bank details on record are outdated, incorrect, closed, or inactive.\nThe insurer asks for updated KYC, PAN, address proof, or current bank proof before releasing the amount, and the matter stalls because the papers submitted do not fully line up.\nThe policyholder changed bank, address, residency status, or name format over the years, but the policy record was never updated cleanly.\nA death-claim or family payout is otherwise moving, but release is blocked because the claimant’s KYC, bank trail, or relationship documentation is not aligned properly with the policy file.\nThe insurer indicates that a payout was attempted earlier, but the credit failed, the cheque was not encashed, or the servicing route was never regularised afterward.\nThe family is told that the amount is payable in principle, but no one has explained exactly which record defects must be corrected before the money can actually move.",
      "Who Typically Needs Help With This?": "Policyholders whose insurer has pointed to KYC, bank, PAN, address, or servicing-record mismatch as the reason the payout is not being released.\nSenior citizens dealing with older LIC or insurer policies where the record has not kept pace with changes in banking, contact details, or compliance requirements.\nWidows, nominees, legal heirs, and family members pursuing insurance money after a death but finding that the payout route is blocked by stale or inconsistent records.\nNRIs whose Indian insurance records no longer match current overseas address, identity, banking, or residency details.\nClients who have already submitted papers more than once but are still receiving repetitive objections without a clear diagnosis of the full mismatch.",
      "How Sahirasta Helps": "Sahirasta begins by identifying the real point of failure in the payout chain. The insurer may use a broad phrase like “KYC pending” or “bank mismatch,” but that does not always tell the full story. The actual issue may involve an old closed account, inconsistent PAN trail, outdated address, partial KYC update, claimant-side identity mismatch, or an older policy record that was never regularised after a change in family or banking circumstances.\nOnce the likely block is identified, Sahirasta helps organise the correction file in a practical sequence. That may include current identity proof, address proof, PAN, bank proof, claimant documents, old and new payout details, and insurer correspondence already received. The aim is to reduce the scatter that causes insurers to keep raising objections one by one instead of seeing one coherent correction trail.\nWhere the case overlaps with survival-benefit non-receipt, old LIC or insurer record mismatch, nominee confusion, death-claim processing, or missing policy documents, Sahirasta helps separate those layers so the payout blockage is not treated as a vague servicing issue. That often makes the next action far more precise.\nThe goal is not to promise instant release from one update. The goal is to help the insurer-facing file become consistent enough that payment can move through a clean route instead of remaining stuck between branch instructions, compliance queries, and incomplete record updates.",
      "Documents Usually Required": "The exact documents depend on the insurer, the policy stage, and whether the policyholder is alive or represented by family. Commonly relevant documents include:\nPolicy bond, policy number, premium receipts, payout intimation, claim communication, or any insurer record showing that an amount is due or pending release.\nPAN, Aadhaar, passport, address proof, overseas identity or address proof where relevant, and any other current KYC documents required for the policyholder or claimant.\nCancelled cheque, passbook copy, bank statement, banker certificate, closed-account proof, new-account proof, or any record showing failed or outdated payout routing.\nOld and current address or identity records where they help connect the present record with the historical policy file.\nDeath certificate, nominee proof, legal-heir papers, claimant identity documents, and entitlement support where the payout issue arises after the policyholder’s death.\nAny insurer letters, emails, SMS alerts, objection notes, branch communication, or servicing memos showing what mismatch or compliance issue the insurer has already flagged.",
      "Why These Cases Get Stuck": "These matters often drag on because the visible defect is only one part of the problem. A client may update the bank account but forget that PAN, address, or claimant identity still does not match the older file. The insurer then raises the next objection, and the client feels as though the goalpost keeps moving. In reality, the full record was never cleaned up together.\nAnother reason is that families often underestimate how much old insurance files depend on consistency. If the insurer sees one name on the policy, another on the bank record, an old address in the system, and incomplete KYC on the claimant side, the payout may remain stuck even where the policy itself is not in dispute.\nOlder LIC and insurer cases are especially prone to this because the record may have moved through paper servicing, branch transfers, manual updates, partial digitisation, and later compliance checks. By the time a payout is pursued seriously, several small defects may be sitting on top of each other.\nThese cases also become frustrating because the insurer may describe them as routine servicing matters, while the family experiences them as a near-complete block. That mismatch in perception is exactly why the file needs to be diagnosed properly instead of updated in fragments.",
      "Special Notes for Widows, Legal Heirs, and NRIs": "Widows and family members often encounter this problem at the worst possible stage: after they have already done the emotional and documentary work of identifying the policy and pursuing the claim, only to be told that the payout still cannot be released because the servicing record or banking route is not in order.\nLegal heirs may face a double burden where the policyholder’s old record was already outdated before death and the claimant now has to regularise both entitlement and payout details together. In such cases the file has to be built more carefully than a simple update request.\nNRIs face the additional complexity of linking current overseas identity, address, and banking or remittance-related records with an old Indian insurance file. These cases are often workable, but only if the sequence of corrections is handled with discipline and the insurer’s queries are addressed coherently.",
      "Frequently Asked Questions": "What does it mean when an insurer says payout is blocked because of KYC or bank mismatch?\nIt usually means the insurer is not satisfied that the amount can be safely released on the basis of the current banking and identity records available in the file.\nCan an old closed bank account stop insurance money from being released?\nYes. If the insurer is still holding outdated payout instructions, the release can fail or remain pending until the correct bank route is regularised properly.\nWhat if I already submitted new bank details but the insurer is still objecting?\nThat often means the problem is broader than one bank change. PAN, address, claimant identity, or other linked records may still not align with the old policy file.\nCan widows or legal heirs handle payout-blockage issues after the policyholder’s death?\nOften yes, but the file may need both entitlement proof and record-regularisation support before the insurer will release the amount.\nCan NRIs fix insurer KYC or bank-record issues without repeated travel?\nMany cases can be worked remotely, though older files usually need more careful document coordination and clearer sequencing than routine servicing requests.",
      "Final Call to Action": "If insurance money is due but cannot move because the bank route, KYC trail, address record, or claimant details do not match, repeating the same partial update rarely solves the problem. The file has to be brought back into alignment first.\nWhether the issue is an old closed bank account, stale KYC, address mismatch, incomplete claimant record, or a larger payout-release problem inside an older policy file, Sahirasta can review the case and help identify the likely route to move it forward.\nRequest a Case Review"
    },
    "slug": "insurance-kyc-bank-mismatch-blocking-payout"
  }
]
JSON;

    $decoded = json_decode($json, true);

    return is_array($decoded) ? $decoded : [];
}

function sahirastha_extract_hero_fields(string $heroText): array
{
    $fields = [
        'headline' => '',
        'subheadline' => '',
        'support_line' => '',
        'primary_cta' => 'Request a Case Review',
        'secondary_cta' => '',
    ];

    foreach (preg_split('/\R+/', trim($heroText)) as $line) {
        $line = trim($line);
        if ($line === '') {
            continue;
        }

        if (str_starts_with($line, 'Page headline:')) {
            $fields['headline'] = trim(substr($line, strlen('Page headline:')));
            continue;
        }

        if (str_starts_with($line, 'Subheadline:')) {
            $fields['subheadline'] = trim(substr($line, strlen('Subheadline:')));
            continue;
        }

        if (str_starts_with($line, 'Support line:')) {
            $fields['support_line'] = trim(substr($line, strlen('Support line:')));
            continue;
        }

        if (str_starts_with($line, 'Primary CTA:')) {
            $fields['primary_cta'] = trim(substr($line, strlen('Primary CTA:')));
            continue;
        }

        if (str_starts_with($line, 'Secondary CTA:')) {
            $fields['secondary_cta'] = trim(substr($line, strlen('Secondary CTA:')));
            continue;
        }
    }

    return $fields;
}

function sahirastha_render_section_text(string $text, bool $isFaq = false): string
{
    $lines = array_values(array_filter(array_map('trim', preg_split('/\R+/', trim($text)))));
    if ($lines === []) {
        return '';
    }

    $html = '';

    if ($isFaq) {
        for ($i = 0; $i < count($lines); $i += 2) {
            $q = $lines[$i] ?? '';
            $a = $lines[$i + 1] ?? '';
            if ($q !== '') {
                $html .= '<h3>' . esc_html($q) . '</h3>';
            }
            if ($a !== '') {
                $html .= '<p>' . esc_html($a) . '</p>';
            }
        }

        return $html;
    }

    $listMode = false;
    foreach ($lines as $line) {
        $looksLikeLead = str_ends_with($line, 'include:') || str_ends_with($line, 'include') || str_ends_with($line, 'documents include:');
        if ($looksLikeLead) {
            if ($listMode) {
                $html .= '</ul>';
                $listMode = false;
            }
            $html .= '<p>' . esc_html($line) . '</p>';
            continue;
        }

        $wordCount = str_word_count($line);
        $isLikelyBullet = $wordCount <= 24;

        if ($isLikelyBullet) {
            if (!$listMode) {
                $html .= '<ul>';
                $listMode = true;
            }
            $html .= '<li>' . esc_html($line) . '</li>';
            continue;
        }

        if ($listMode) {
            $html .= '</ul>';
            $listMode = false;
        }

        $html .= '<p>' . esc_html($line) . '</p>';
    }

    if ($listMode) {
        $html .= '</ul>';
    }

    return $html;
}

function sahirastha_build_insurance_service_content(array $service, array $allServices): string
{
    $sections = $service['sections'] ?? [];
    $hero = sahirastha_extract_hero_fields((string) ($sections['Hero Section'] ?? ''));

    $content = '<div class="sahirastha-service-hero">';
    if ($hero['headline'] !== '') {
        $content .= '<h2>' . esc_html($hero['headline']) . '</h2>';
    }
    if ($hero['subheadline'] !== '') {
        $content .= '<p>' . esc_html($hero['subheadline']) . '</p>';
    }
    if ($hero['support_line'] !== '') {
        $content .= '<p>' . esc_html($hero['support_line']) . '</p>';
    }
    $content .= '<p><strong>' . esc_html($hero['primary_cta']) . '</strong></p>';
    if ($hero['secondary_cta'] !== '') {
        $content .= '<p>' . esc_html($hero['secondary_cta']) . '</p>';
    }
    $content .= '</div>';

    foreach ($sections as $sectionTitle => $sectionBody) {
        if ($sectionTitle === 'Hero Section') {
            continue;
        }

        $content .= '<h2>' . esc_html($sectionTitle) . '</h2>';
        $content .= sahirastha_render_section_text((string) $sectionBody, str_contains($sectionTitle, 'Frequently Asked Questions'));
    }

    $crossLinks = [];
    $keywords = [
        'death claim' => 'insurance-death-claim-support',
        'nominee' => 'insurance-nominee-issues',
        'lost policy' => 'insurance-lost-policy-bond',
        'record mismatch' => 'insurance-old-record-mismatch',
        'bank' => 'insurance-kyc-bank-mismatch-blocking-payout',
        'kyc' => 'insurance-kyc-bank-mismatch-blocking-payout',
        'short-settled' => 'insurance-short-settled-claims',
        'survival benefit' => 'insurance-survival-benefit-not-received',
        'rejected' => 'insurance-rejected-claims',
        'policy loan' => 'insurance-policy-loan-complications',
    ];

    $combined = strtolower(wp_strip_all_tags($content));
    foreach ($keywords as $term => $slug) {
        if ($slug === ($service['slug'] ?? '') || !str_contains($combined, $term)) {
            continue;
        }

        foreach ($allServices as $candidate) {
            if (($candidate['slug'] ?? '') !== $slug) {
                continue;
            }

            $crossLinks[$slug] = [
                'title' => $candidate['title'],
                'url' => home_url('/' . $slug . '/'),
            ];
        }
    }

    if ($crossLinks !== []) {
        $content .= '<h2>Related Insurance Service Routes</h2><div class="sahirastha-service-links"><ul>';
        foreach ($crossLinks as $link) {
            $content .= '<li><a href="' . esc_url($link['url']) . '">' . esc_html($link['title']) . '</a></li>';
        }
        $content .= '</ul></div>';
    }

    return $content;
}

function sahirastha_build_services_page_insurance_section(array $services): string
{
    $content = '<h2>Insurance Claims & Recovery</h2>';
    $content .= '<p>This section covers insurance amounts and claim problems that are stuck, delayed, disputed, or blocked by documentation. Choose the route closest to your issue.</p>';
    $content .= '<ul>';

    foreach ($services as $service) {
        $content .= '<li><a href="' . esc_url(home_url('/' . $service['slug'] . '/')) . '"><strong>' . esc_html($service['title']) . '</strong></a></li>';
    }

    $content .= '</ul>';
    $content .= '<p>If your case overlaps across payout, nominee, record mismatch, missing papers, or family-entitlement issues, request a case review and start with the route that appears closest.</p>';

    return $content;
}
